#include "config.h"
#include <lightningd/log.h>

static void db_log_(struct logger *log UNUSED, enum log_level level UNUSED, const struct node_id *node_id UNUSED, bool call_notifier UNUSED, const char *fmt UNUSED, ...)
{
}
#define log_ db_log_

#include "db/bindings.c"
#include "db/db_sqlite3.c"
#include "db/exec.c"
#include "db/utils.c"
#include "wallet/datastore.c"
#include "wallet/db.c"
#include "wallet/wallet.c"
#include "wallet/migrations.c"

#include "test_utils.h"

#include <common/setup.h>
#include <common/utils.h>
#include <lightningd/channel.h>
#include <stdio.h>
#include <unistd.h>

/* AUTOGENERATED MOCKS START */
/* Generated stub for bip32_pubkey */
void bip32_pubkey(struct lightningd *ld UNNEEDED, struct pubkey *pubkey UNNEEDED, u32 index UNNEEDED)
{ fprintf(stderr, "bip32_pubkey called!\n"); abort(); }
/* Generated stub for bip86_pubkey */
void bip86_pubkey(struct lightningd *ld UNNEEDED, struct pubkey *pubkey UNNEEDED, u32 index UNNEEDED)
{ fprintf(stderr, "bip86_pubkey called!\n"); abort(); }
/* Generated stub for bitcoind_getrawblockbyheight_ */
void bitcoind_getrawblockbyheight_(const tal_t *ctx UNNEEDED,
				   struct bitcoind *bitcoind UNNEEDED,
				   u32 height UNNEEDED,
				   void (*cb)(struct bitcoind *bitcoind_ UNNEEDED,
					      u32 height_ UNNEEDED,
					      struct bitcoin_blkid *blkid UNNEEDED,
					      struct bitcoin_block *blk UNNEEDED,
					      void *arg) UNNEEDED,
				   void *arg UNNEEDED)
{ fprintf(stderr, "bitcoind_getrawblockbyheight_ called!\n"); abort(); }
/* Generated stub for chain_mvt_index_created */
u64 chain_mvt_index_created(struct lightningd *ld UNNEEDED,
			    struct db *db UNNEEDED,
			    const struct mvt_account_id *account UNNEEDED,
			    struct amount_msat credit UNNEEDED,
			    struct amount_msat debit UNNEEDED)
{ fprintf(stderr, "chain_mvt_index_created called!\n"); abort(); }
/* Generated stub for channel_by_dbid */
struct channel *channel_by_dbid(struct lightningd *ld UNNEEDED, const u64 dbid UNNEEDED)
{ fprintf(stderr, "channel_by_dbid called!\n"); abort(); }
/* Generated stub for channel_gossip_get_remote_update */
const struct peer_update *channel_gossip_get_remote_update(const struct channel *channel UNNEEDED)
{ fprintf(stderr, "channel_gossip_get_remote_update called!\n"); abort(); }
/* Generated stub for channel_gossip_update */
void channel_gossip_update(struct channel *channel UNNEEDED)
{ fprintf(stderr, "channel_gossip_update called!\n"); abort(); }
/* Generated stub for channel_mvt_index_created */
u64 channel_mvt_index_created(struct lightningd *ld UNNEEDED,
			      struct db *db UNNEEDED,
			      const struct mvt_account_id *account UNNEEDED,
			      struct amount_msat credit UNNEEDED,
			      struct amount_msat debit UNNEEDED)
{ fprintf(stderr, "channel_mvt_index_created called!\n"); abort(); }
/* Generated stub for channel_scid_or_local_alias */
struct short_channel_id channel_scid_or_local_alias(const struct channel *chan UNNEEDED)
{ fprintf(stderr, "channel_scid_or_local_alias called!\n"); abort(); }
/* Generated stub for channel_state_name */
const char *channel_state_name(const struct channel *channel UNNEEDED)
{ fprintf(stderr, "channel_state_name called!\n"); abort(); }
/* Generated stub for connect_htlc_in */
void connect_htlc_in(struct htlc_in_map *map UNNEEDED, struct htlc_in *hin UNNEEDED)
{ fprintf(stderr, "connect_htlc_in called!\n"); abort(); }
/* Generated stub for connect_htlc_out */
void connect_htlc_out(struct htlc_out_map *map UNNEEDED, struct htlc_out *hout UNNEEDED)
{ fprintf(stderr, "connect_htlc_out called!\n"); abort(); }
/* Generated stub for fatal */
void   fatal(const char *fmt UNNEEDED, ...)
{ fprintf(stderr, "fatal called!\n"); abort(); }
/* Generated stub for fatal_vfmt */
void  fatal_vfmt(const char *fmt UNNEEDED, va_list ap UNNEEDED)
{ fprintf(stderr, "fatal_vfmt called!\n"); abort(); }
/* Generated stub for find_peer_by_dbid */
struct peer *find_peer_by_dbid(struct lightningd *ld UNNEEDED, u64 dbid UNNEEDED)
{ fprintf(stderr, "find_peer_by_dbid called!\n"); abort(); }
/* Generated stub for forward_index_created */
u64 forward_index_created(struct lightningd *ld UNNEEDED,
			  enum forward_status status UNNEEDED,
			  struct short_channel_id in_channel UNNEEDED,
			  u64 in_htlc_id UNNEEDED,
			  struct amount_msat in_amount UNNEEDED,
			  const struct short_channel_id *out_channel UNNEEDED)
{ fprintf(stderr, "forward_index_created called!\n"); abort(); }
/* Generated stub for forward_index_deleted */
void forward_index_deleted(struct lightningd *ld UNNEEDED,
			   enum forward_status status UNNEEDED,
			   struct short_channel_id in_channel UNNEEDED,
			   u64 in_htlc_id UNNEEDED,
			   const struct amount_msat *in_amount UNNEEDED,
			   const struct short_channel_id *out_channel UNNEEDED)
{ fprintf(stderr, "forward_index_deleted called!\n"); abort(); }
/* Generated stub for forward_index_update_status */
u64 forward_index_update_status(struct lightningd *ld UNNEEDED,
				enum forward_status status UNNEEDED,
				struct short_channel_id in_channel UNNEEDED,
				u64 in_htlc_id UNNEEDED,
				struct amount_msat in_amount UNNEEDED,
				const struct short_channel_id *out_channel UNNEEDED)
{ fprintf(stderr, "forward_index_update_status called!\n"); abort(); }
/* Generated stub for fromwire_hsmd_get_channel_basepoints_reply */
bool fromwire_hsmd_get_channel_basepoints_reply(const void *p UNNEEDED, struct basepoints *basepoints UNNEEDED, struct pubkey *funding_pubkey UNNEEDED)
{ fprintf(stderr, "fromwire_hsmd_get_channel_basepoints_reply called!\n"); abort(); }
/* Generated stub for fromwire_hsmd_get_output_scriptpubkey_reply */
bool fromwire_hsmd_get_output_scriptpubkey_reply(const tal_t *ctx UNNEEDED, const void *p UNNEEDED, u8 **script UNNEEDED)
{ fprintf(stderr, "fromwire_hsmd_get_output_scriptpubkey_reply called!\n"); abort(); }
/* Generated stub for get_channel_basepoints */
void get_channel_basepoints(struct lightningd *ld UNNEEDED,
			    const struct node_id *peer_id UNNEEDED,
			    const u64 dbid UNNEEDED,
			    struct basepoints *local_basepoints UNNEEDED,
			    struct pubkey *local_funding_pubkey UNNEEDED)
{ fprintf(stderr, "get_channel_basepoints called!\n"); abort(); }
/* Generated stub for hash_cid */
size_t hash_cid(const struct channel_id *cid UNNEEDED)
{ fprintf(stderr, "hash_cid called!\n"); abort(); }
/* Generated stub for htlc_in_check */
struct htlc_in *htlc_in_check(const struct htlc_in *hin UNNEEDED, const char *abortstr UNNEEDED)
{ fprintf(stderr, "htlc_in_check called!\n"); abort(); }
/* Generated stub for htlc_out_connect_htlc_in */
void htlc_out_connect_htlc_in(struct htlc_out *hout UNNEEDED, struct htlc_in *hin UNNEEDED)
{ fprintf(stderr, "htlc_out_connect_htlc_in called!\n"); abort(); }
/* Generated stub for htlcs_index_created */
u64 htlcs_index_created(struct lightningd *ld UNNEEDED,
			u64 htlc_id UNNEEDED,
			const struct channel *channel UNNEEDED,
			const struct sha256 *payment_hash UNNEEDED,
			enum side owner UNNEEDED,
			u32 expiry UNNEEDED,
			struct amount_msat amount UNNEEDED,
			enum htlc_state hstate UNNEEDED)
{ fprintf(stderr, "htlcs_index_created called!\n"); abort(); }
/* Generated stub for htlcs_index_deleted */
void htlcs_index_deleted(struct lightningd *ld UNNEEDED,
			 const struct channel *channel UNNEEDED,
			 u64 num_deleted UNNEEDED)
{ fprintf(stderr, "htlcs_index_deleted called!\n"); abort(); }
/* Generated stub for htlcs_index_update_status */
u64 htlcs_index_update_status(struct lightningd *ld UNNEEDED,
			      u64 htlc_id UNNEEDED,
			      const struct channel *channel UNNEEDED,
			      const struct sha256 *payment_hash UNNEEDED,
			      enum side owner UNNEEDED,
			      u32 expiry UNNEEDED,
			      struct amount_msat amount UNNEEDED,
			      enum htlc_state hstate UNNEEDED)
{ fprintf(stderr, "htlcs_index_update_status called!\n"); abort(); }
/* Generated stub for inflight_set_last_tx */
void inflight_set_last_tx(struct channel_inflight *inflight UNNEEDED,
		          struct bitcoin_tx *last_tx STEALS UNNEEDED,
		          const struct bitcoin_signature last_sig UNNEEDED)
{ fprintf(stderr, "inflight_set_last_tx called!\n"); abort(); }
/* Generated stub for invoices_new */
struct invoices *invoices_new(const tal_t *ctx UNNEEDED,
			      struct wallet *wallet UNNEEDED,
			      struct timers *timers UNNEEDED)
{ fprintf(stderr, "invoices_new called!\n"); abort(); }
/* Generated stub for logv */
void logv(struct logger *logger UNNEEDED, enum log_level level UNNEEDED, const struct node_id *node_id UNNEEDED,
	  bool call_notifier UNNEEDED, const char *fmt UNNEEDED, va_list ap UNNEEDED)
{ fprintf(stderr, "logv called!\n"); abort(); }
/* Generated stub for new_channel */
struct channel *new_channel(struct peer *peer UNNEEDED, u64 dbid UNNEEDED,
			    /* NULL or stolen */
			    struct wallet_shachain *their_shachain STEALS UNNEEDED,
			    enum channel_state state UNNEEDED,
			    enum side opener UNNEEDED,
			    /* NULL or stolen */
			    struct logger *log STEALS UNNEEDED,
			    const char *transient_billboard TAKES UNNEEDED,
			    u8 channel_flags UNNEEDED,
			    bool req_confirmed_ins_local UNNEEDED,
			    bool req_confirmed_ins_remote UNNEEDED,
			    const struct channel_config *our_config UNNEEDED,
			    u32 minimum_depth UNNEEDED,
			    u64 next_index_local UNNEEDED,
			    u64 next_index_remote UNNEEDED,
			    u64 next_htlc_id UNNEEDED,
			    const struct bitcoin_outpoint *funding UNNEEDED,
			    struct amount_sat funding_sats UNNEEDED,
			    struct amount_msat push UNNEEDED,
			    struct amount_sat our_funds UNNEEDED,
			    bool remote_channel_ready UNNEEDED,
			    /* NULL or stolen */
			    struct short_channel_id *scid TAKES UNNEEDED,
			    struct short_channel_id *old_scids TAKES UNNEEDED,
			    struct short_channel_id alias_local UNNEEDED,
			    struct short_channel_id *alias_remote STEALS UNNEEDED,
			    struct channel_id *cid UNNEEDED,
			    struct amount_msat our_msatoshi UNNEEDED,
			    struct amount_msat msatoshi_to_us_min UNNEEDED,
			    struct amount_msat msatoshi_to_us_max UNNEEDED,
			    struct bitcoin_tx *last_tx STEALS UNNEEDED,
			    const struct bitcoin_signature *last_sig UNNEEDED,
			    /* NULL or stolen */
			    const struct bitcoin_signature *last_htlc_sigs STEALS UNNEEDED,
			    const struct channel_info *channel_info UNNEEDED,
			    const struct fee_states *fee_states TAKES UNNEEDED,
			    /* NULL or stolen */
			    u8 *remote_shutdown_scriptpubkey STEALS UNNEEDED,
			    const u8 *local_shutdown_scriptpubkey UNNEEDED,
			    u64 final_key_idx UNNEEDED,
			    bool last_was_revoke UNNEEDED,
			    /* NULL or stolen */
			    struct changed_htlc *last_sent_commit STEALS UNNEEDED,
			    u32 first_blocknum UNNEEDED,
			    u32 min_possible_feerate UNNEEDED,
			    u32 max_possible_feerate UNNEEDED,
			    const struct basepoints *local_basepoints UNNEEDED,
			    const struct pubkey *local_funding_pubkey UNNEEDED,
			    bool has_future_per_commitment_point UNNEEDED,
			    u32 feerate_base UNNEEDED,
			    u32 feerate_ppm UNNEEDED,
			    /* NULL or stolen */
			    const u8 *remote_upfront_shutdown_script STEALS UNNEEDED,
			    u64 local_static_remotekey_start UNNEEDED,
			    u64 remote_static_remotekey_start UNNEEDED,
			    const struct channel_type *type STEALS UNNEEDED,
			    enum side closer UNNEEDED,
			    u32 close_attempt_height UNNEEDED,
			    enum state_change reason UNNEEDED,
			    /* NULL or stolen */
			    const struct bitcoin_outpoint *shutdown_wrong_funding STEALS UNNEEDED,
			    const struct height_states *height_states TAKES UNNEEDED,
			    u32 lease_expiry UNNEEDED,
			    secp256k1_ecdsa_signature *lease_commit_sig STEALS UNNEEDED,
			    u32 lease_chan_max_msat UNNEEDED,
			    u16 lease_chan_max_ppt UNNEEDED,
			    struct amount_msat htlc_minimum_msat UNNEEDED,
			    struct amount_msat htlc_maximum_msat UNNEEDED,
			    bool ignore_fee_limits UNNEEDED,
			    /* NULL or stolen */
			    struct peer_update *peer_update STEALS UNNEEDED,
			    u64 last_stable_connection UNNEEDED,
			    const struct channel_stats *stats UNNEEDED,
			    struct channel_state_change **state_changes STEALS UNNEEDED,
			    const struct wally_psbt *funding_psbt STEALS UNNEEDED,
			    bool withheld UNNEEDED)
{ fprintf(stderr, "new_channel called!\n"); abort(); }
/* Generated stub for new_channel_state_change */
struct channel_state_change *new_channel_state_change(const tal_t *ctx UNNEEDED,
						      struct timeabs timestamp UNNEEDED,
						      enum channel_state old_state UNNEEDED,
						      enum channel_state new_state UNNEEDED,
						      enum state_change cause UNNEEDED,
						      const char *message TAKES UNNEEDED)
{ fprintf(stderr, "new_channel_state_change called!\n"); abort(); }
/* Generated stub for new_inflight */
struct channel_inflight *new_inflight(struct channel *channel UNNEEDED,
	     struct pubkey *remote_funding STEALS UNNEEDED,
	     const struct bitcoin_outpoint *funding_outpoint UNNEEDED,
	     u32 funding_feerate UNNEEDED,
	     struct amount_sat funding_sat UNNEEDED,
	     struct amount_sat our_funds UNNEEDED,
	     struct wally_psbt *funding_psbt STEALS UNNEEDED,
	     const u32 lease_expiry UNNEEDED,
	     const secp256k1_ecdsa_signature *lease_commit_sig UNNEEDED,
	     const u32 lease_chan_max_msat UNNEEDED,
	     const u16 lease_chan_max_ppt UNNEEDED,
	     const u32 lease_blockheight_start UNNEEDED,
	     const struct amount_msat lease_fee UNNEEDED,
	     const struct amount_sat lease_amt UNNEEDED,
	     s64 splice_amnt UNNEEDED,
	     bool i_am_initiator UNNEEDED,
	     bool force_sign_first UNNEEDED,
	     bool i_sent_sigs UNNEEDED)
{ fprintf(stderr, "new_inflight called!\n"); abort(); }
/* Generated stub for new_logger */
struct logger *new_logger(const tal_t *ctx UNNEEDED, struct log_book *record UNNEEDED,
			  const struct node_id *default_node_id UNNEEDED,
			  const char *fmt UNNEEDED, ...)
{ fprintf(stderr, "new_logger called!\n"); abort(); }
/* Generated stub for new_peer */
struct peer *new_peer(struct lightningd *ld UNNEEDED, u64 dbid UNNEEDED,
		      const struct node_id *id UNNEEDED,
		      const struct wireaddr_internal *addr UNNEEDED,
		      const struct wireaddr *last_known_addr UNNEEDED,
		      const u8 *their_features TAKES UNNEEDED,
		      bool connected_incoming UNNEEDED)
{ fprintf(stderr, "new_peer called!\n"); abort(); }
/* Generated stub for notify_chain_mvt */
void notify_chain_mvt(struct lightningd *ld UNNEEDED,
		      const struct chain_coin_mvt *chain_mvt UNNEEDED,
		      u64 id UNNEEDED)
{ fprintf(stderr, "notify_chain_mvt called!\n"); abort(); }
/* Generated stub for notify_channel_mvt */
void notify_channel_mvt(struct lightningd *ld UNNEEDED,
			const struct channel_coin_mvt *chan_mvt UNNEEDED,
			u64 id UNNEEDED)
{ fprintf(stderr, "notify_channel_mvt called!\n"); abort(); }
/* Generated stub for notify_forward_event */
void notify_forward_event(struct lightningd *ld UNNEEDED,
			  const struct htlc_in *in UNNEEDED,
			  /* May be NULL if we don't know. */
			  const struct short_channel_id *scid_out UNNEEDED,
			  /* May be NULL. */
			  const struct amount_msat *amount_out UNNEEDED,
			  enum forward_status state UNNEEDED,
			  enum onion_wire failcode UNNEEDED,
			  struct timeabs *resolved_time UNNEEDED,
			  enum forward_style forward_style UNNEEDED,
			  u64 created_index UNNEEDED,
			  u64 updated_index UNNEEDED)
{ fprintf(stderr, "notify_forward_event called!\n"); abort(); }
/* Generated stub for outpointfilter_add */
void outpointfilter_add(struct outpointfilter *of UNNEEDED,
			const struct bitcoin_outpoint *outpoint UNNEEDED)
{ fprintf(stderr, "outpointfilter_add called!\n"); abort(); }
/* Generated stub for outpointfilter_matches */
bool outpointfilter_matches(struct outpointfilter *of UNNEEDED,
			    const struct bitcoin_outpoint *outpoint UNNEEDED)
{ fprintf(stderr, "outpointfilter_matches called!\n"); abort(); }
/* Generated stub for outpointfilter_new */
struct outpointfilter *outpointfilter_new(tal_t *ctx UNNEEDED)
{ fprintf(stderr, "outpointfilter_new called!\n"); abort(); }
/* Generated stub for outpointfilter_remove */
void outpointfilter_remove(struct outpointfilter *of UNNEEDED,
			   const struct bitcoin_outpoint *outpoint UNNEEDED)
{ fprintf(stderr, "outpointfilter_remove called!\n"); abort(); }
/* Generated stub for peer_set_dbid */
void peer_set_dbid(struct peer *peer UNNEEDED, u64 dbid UNNEEDED)
{ fprintf(stderr, "peer_set_dbid called!\n"); abort(); }
/* Generated stub for psbt_fixup */
const u8 *psbt_fixup(const tal_t *ctx UNNEEDED, const u8 *psbtblob UNNEEDED)
{ fprintf(stderr, "psbt_fixup called!\n"); abort(); }
/* Generated stub for remove_htlc_in_by_dbid */
struct htlc_in *remove_htlc_in_by_dbid(struct htlc_in_map *remaining_htlcs_in UNNEEDED,
				       u64 dbid UNNEEDED)
{ fprintf(stderr, "remove_htlc_in_by_dbid called!\n"); abort(); }
/* Generated stub for rune_unique_id */
u64 rune_unique_id(const struct rune *rune UNNEEDED)
{ fprintf(stderr, "rune_unique_id called!\n"); abort(); }
/* Generated stub for sendpay_index_created */
u64 sendpay_index_created(struct lightningd *ld UNNEEDED,
			  const struct sha256 *payment_hash UNNEEDED,
			  u64 partid UNNEEDED,
			  u64 groupid UNNEEDED,
			  enum payment_status status UNNEEDED)
{ fprintf(stderr, "sendpay_index_created called!\n"); abort(); }
/* Generated stub for sendpay_index_deleted */
void sendpay_index_deleted(struct lightningd *ld UNNEEDED,
			   const struct sha256 *payment_hash UNNEEDED,
			   u64 partid UNNEEDED,
			   u64 groupid UNNEEDED,
			   enum payment_status status UNNEEDED)
{ fprintf(stderr, "sendpay_index_deleted called!\n"); abort(); }
/* Generated stub for sendpay_index_update_status */
u64 sendpay_index_update_status(struct lightningd *ld UNNEEDED,
				const struct sha256 *payment_hash UNNEEDED,
				u64 partid UNNEEDED,
				u64 groupid UNNEEDED,
				enum payment_status status UNNEEDED)
{ fprintf(stderr, "sendpay_index_update_status called!\n"); abort(); }
/* Generated stub for towire_hsmd_get_channel_basepoints */
u8 *towire_hsmd_get_channel_basepoints(const tal_t *ctx UNNEEDED, const struct node_id *peerid UNNEEDED, u64 dbid UNNEEDED)
{ fprintf(stderr, "towire_hsmd_get_channel_basepoints called!\n"); abort(); }
/* Generated stub for towire_hsmd_get_output_scriptpubkey */
u8 *towire_hsmd_get_output_scriptpubkey(const tal_t *ctx UNNEEDED, u64 channel_id UNNEEDED, const struct node_id *peer_id UNNEEDED, const struct pubkey *commitment_point UNNEEDED)
{ fprintf(stderr, "towire_hsmd_get_output_scriptpubkey called!\n"); abort(); }
/* Generated stub for wait_index_increment */
u64  wait_index_increment(struct lightningd *ld UNNEEDED,
				       struct db *db UNNEEDED,
				       enum wait_subsystem subsystem UNNEEDED,
				       enum wait_index index UNNEEDED,
				       ...)
{ fprintf(stderr, "wait_index_increment called!\n"); abort(); }
/* Generated stub for wait_index_name */
const char *wait_index_name(enum wait_index index UNNEEDED)
{ fprintf(stderr, "wait_index_name called!\n"); abort(); }
/* Generated stub for wait_subsystem_name */
const char *wait_subsystem_name(enum wait_subsystem subsystem UNNEEDED)
{ fprintf(stderr, "wait_subsystem_name called!\n"); abort(); }
/* AUTOGENERATED MOCKS END */

void plugin_hook_db_sync(struct db *db UNNEEDED)
{
}

void migrate_from_account_db(struct lightningd *ld UNNEEDED, struct db *db UNNEEDED)
{
}

static struct db *create_test_db(void)
{
	struct db *db;
	char *dsn, *filename;

	int fd = tmpdir_mkstemp(tmpctx, "ldb-XXXXXX", &filename);
	if (fd == -1)
		return NULL;
	close(fd);

	dsn = tal_fmt(NULL, "sqlite3://%s", filename);
	tal_free(filename);
	db = db_open(NULL, dsn, true, true, db_error, (struct lightningd *)NULL);
	db->data_version = 0;
	db->report_changes_fn = NULL;

	tal_free(dsn);
	return db;
}


/* fork #125 unit rails (lightning-playground #125): pin the sent_commitsigs
 * persistence contract at UNIT level — the crash-resume replay is only
 * sound if these hold:
 *   must-accept : save -> get round-trips the EXACT batch bytes + number;
 *                 a re-save at a new number REPLACES (one row per channel,
 *                 latest signed batch is what a resume must replay).
 *   must-refuse : absent row reads NULL (first-time-through unchanged);
 *                 a stale row (different commitnum) is reported FAITHFULLY
 *                 so the fetch handler's gate (stored != wanted => absent)
 *                 can never replay stale bytes. */

static bool test_sent_commitsig_roundtrip(struct lightningd *ld)
{
	struct db *db = create_test_db();
	struct wallet *w = tal(db, struct wallet);
	u8 *got;
	u64 commitnum;
	const u8 batch[] = { 0xde, 0xad, 0xbe, 0xef, 0x00, 0x42 };

	CHECK(db != NULL);
	w->db = db;

	db_begin_transaction(db);
	db_migrate(ld, db, NULL);

	wallet_sent_commitsig_save(w, 42, 0, batch, sizeof(batch));
	got = (u8 *)wallet_sent_commitsig_get(tmpctx, w, 42, &commitnum);
	CHECK(got != NULL);
	CHECK(commitnum == 0);
	CHECK(tal_bytelen(got) == sizeof(batch));
	CHECK(memcmp(got, batch, sizeof(batch)) == 0);
	db_commit_transaction(db);

	tal_free(db);
	return true;
}

static bool test_sent_commitsig_upsert_latest_wins(struct lightningd *ld)
{
	struct db *db = create_test_db();
	struct wallet *w = tal(db, struct wallet);
	u8 *got;
	u64 commitnum;
	const u8 first[] = { 0x01 }, second[] = { 0x02, 0x03 };

	CHECK(db != NULL);
	w->db = db;

	db_begin_transaction(db);
	db_migrate(ld, db, NULL);

	wallet_sent_commitsig_save(w, 7, 0, first, sizeof(first));
	wallet_sent_commitsig_save(w, 7, 1, second, sizeof(second));
	got = (u8 *)wallet_sent_commitsig_get(tmpctx, w, 7, &commitnum);
	/* one row per channel: the LATEST signed batch is authoritative */
	CHECK(got != NULL);
	CHECK(commitnum == 1);
	CHECK(tal_bytelen(got) == sizeof(second));
	CHECK(memcmp(got, second, sizeof(second)) == 0);
	db_commit_transaction(db);

	tal_free(db);
	return true;
}

static bool test_sent_commitsig_absent_is_null(struct lightningd *ld)
{
	struct db *db = create_test_db();
	struct wallet *w = tal(db, struct wallet);
	u64 commitnum = 99;

	CHECK(db != NULL);
	w->db = db;

	db_begin_transaction(db);
	db_migrate(ld, db, NULL);

	/* first-time-through: nothing stored -> no replay, fall back to sign */
	CHECK(wallet_sent_commitsig_get(tmpctx, w, 1234, &commitnum) == NULL);
	/* commitnum must not be touched into looking valid */
	CHECK(commitnum == 99);
	db_commit_transaction(db);

	tal_free(db);
	return true;
}

static bool test_sent_commitsig_stale_row_is_inert(struct lightningd *ld)
{
	struct db *db = create_test_db();
	struct wallet *w = tal(db, struct wallet);
	const u8 *batch;
	u64 stored_commitnum, want_commitnum = 0;
	const u8 stale[] = { 0xaa };

	CHECK(db != NULL);
	w->db = db;

	db_begin_transaction(db);
	db_migrate(ld, db, NULL);

	/* a row left over from an EARLIER number must never satisfy a fetch
	 * for a different number: replicate the handler gate exactly and
	 * assert it resolves to "absent" (the must-refuse rail). */
	wallet_sent_commitsig_save(w, 9, 5, stale, sizeof(stale));
	batch = wallet_sent_commitsig_get(tmpctx, w, 9, &stored_commitnum);
	CHECK(batch != NULL);
	CHECK(stored_commitnum == 5);
	if (batch && stored_commitnum != want_commitnum)
		batch = NULL;
	CHECK(batch == NULL);
	db_commit_transaction(db);

	tal_free(db);
	return true;
}

int main(int argc, char *argv[])
{
	bool ok = true;
	/* Dummy for migration hooks */
	struct lightningd *ld = tal(NULL, struct lightningd);

	common_setup(argv[0]);
	ld->config = test_config;

	/* We do a runtime test here, so we still check compile! */
	if (HAVE_SQLITE3) {
		ok &= test_sent_commitsig_roundtrip(ld);
		ok &= test_sent_commitsig_upsert_latest_wins(ld);
		ok &= test_sent_commitsig_absent_is_null(ld);
		ok &= test_sent_commitsig_stale_row_is_inert(ld);
	}

	tal_free(ld);
	common_shutdown();
	trace_cleanup();
	return !ok;
}
